In [65]:
import pandas as pd
import numpy as np

In [66]:
data=pd.read_csv("instagram_reach.csv")

In [67]:
data

,Unnamed: 0,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139
1,1,2,drgorillapaints,We all know where it’s going. We just have to ...,880,#deck .#mac #macintosh#sayhello #apple #steve...,2 hours,23
2,2,3,aitrading_official,Alexander Barinov: 4 years as CFO in multinati...,255,#whoiswho #aitrading #ai #aitradingteam#instat...,2 hours,25
3,3,4,opensourcedworkplace,sfad,340,#iot #cre#workplace #CDO #bigdata #technology#...,3 hours,49
4,4,5,crea.vision,Ever missed a call while your phone was chargi...,304,#instamachinelearning #instabigdata#instamarke...,3 hours,30
...,...,...,...,...,...,...,...,...
95,8,19,michaelgarza__,"328 S. Wetherly Drive, Beverly Hills, CA 90212...",614,#beverlyhills #realestate#losangelesrealestate...,3 hours,31
96,9,21,dvlp_search,Credit @tristankappel To find more dvlp follow...,450,#workspace #work #developer#development #devel...,3 hours,42
97,10,22,ecom.space,We are coming up with the Best 21 Books that w...,182,#books #book #motivation #inspiration #life#bo...,3 hours,10
98,11,24,lb3enterprises,We’re only paid to move dirt once. It’s not ju...,2039,#heavyequipment #underconstruction#dozer #real...,3 hours,222
99,12,25,palmariusdev,Obtén tu tienda en línea ahora.,741,#marketing #programming#development #desarroll...,3 hours,109

In [68]:
data.head()

,Unnamed: 0,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes
0,0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139
1,1,2,drgorillapaints,We all know where it’s going. We just have to ...,880,#deck .#mac #macintosh#sayhello #apple #steve...,2 hours,23
2,2,3,aitrading_official,Alexander Barinov: 4 years as CFO in multinati...,255,#whoiswho #aitrading #ai #aitradingteam#instat...,2 hours,25
3,3,4,opensourcedworkplace,sfad,340,#iot #cre#workplace #CDO #bigdata #technology#...,3 hours,49
4,4,5,crea.vision,Ever missed a call while your phone was chargi...,304,#instamachinelearning #instabigdata#instamarke...,3 hours,30

In [69]:
data.describe()

       Unnamed: 0        S.No   Followers      Likes
count  100.000000  100.000000   100.00000  100.00000
mean     8.940000   16.240000   961.96000   46.48000
std      6.639064    7.384286  1014.62567   55.08698
min      0.000000    1.000000    11.00000    8.00000
25%      4.000000   10.750000   252.75000   19.00000
50%      8.000000   16.500000   612.00000   29.00000
75%     12.250000   22.250000  1197.00000   46.00000
max     26.000000   30.000000  4496.00000  349.00000

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         100 non-null    int64
 1   S.No               100 non-null    int64
 2   USERNAME           100 non-null    object
 3   Caption            94 non-null     object
 4   Followers          100 non-null    int64
 5   Hashtags           100 non-null    object
 6   Time since posted  100 non-null    object
 7   Likes              100 non-null    int64
dtypes: int64(4), object(4)
memory usage: 6.4+ KB

In [71]:
data.shape

(100, 8)

In [72]:
data.isnull()

,Unnamed: 0,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False

In [73]:
data.isnull().sum()

Unnamed: 0           0
S.No                 0
USERNAME             0
Caption              6
Followers            0
Hashtags             0
Time since posted    0
Likes                0
dtype: int64

In [74]:
# Handle missing values
data.dropna(inplace=True)

In [75]:
data.shape

(94, 8)

In [76]:
# Encode categorical features
data = pd.get_dummies(data, columns=['USERNAME', 'Caption', 'Hashtags'], drop_first=True)

In [95]:
# Encode categorical features
data = pd.get_dummies(data, columns=['Time since posted'], drop_first=True)

KeyError: "None of [Index(['Time since posted'], dtype='object')] are in the [columns]"

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
# Scale numerical features
scaler = StandardScaler()
data[['Followers']] = scaler.fit_transform(data[['Followers']])

In [79]:
X = data.drop(['Likes', 'Time since posted'], axis=1)

In [80]:
y_likes = data['Likes']

In [81]:
y_time_since_posted = data['Time since posted']

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
X_train, X_test, y_train_likes, y_test_likes, y_train_time, y_test_time = train_test_split(X, y_likes, y_time_since_posted, 
                                                                                           test_size=0.2, random_state=42)

In [84]:
X_train

,Unnamed: 0,S.No,Followers,USERNAME__linda_smith567,USERNAME_ah_studio_,USERNAME_aitrading_official,USERNAME_ale_borba,USERNAME_alpha_mentor_,USERNAME_amjstaffing,USERNAME_anki7singh,...,Hashtags_#whoiswho #aitrading #ai #aitradingteam#instateam #instapeople #ai #trading#artificialintelligence #crypto#cryptocurrency #blockchain #tradingforex#forex #fiatmoney #coins #machinelearning#userexperience #instamachinelearning#instabigdata #instamarketing#artificialintelligence #deeplearning#datascience #industry #marketing#bigdata #datascience #machinelearning#ml,Hashtags_#workspace #work #developer#development #developerlife #apple #imac#macbook #macbookpro #blackandwhite#coder #code #coding #html #css #php#wordpress #javascript #dvlp_search #linux#ubuntu #webdeveloper #webdev#webdevelopment #dev #coder #coding#code,Hashtags_#worldcode #coding#python #codeaholics #rstudio #codinglife#worldofprogrammers #datascience#machinelearning #dataviz #data #statistics#macbookpro #peoplewhocode#codeismylife #datavisualization#artificialintelligence #digitalnomads#digitalnomad #travel,Hashtags_#youtube #applemusic #itunes#soundcloud #spinrilla #spotify #bigdata#blockchain #dontbandwagonlater,Hashtags_#любовь #gm #sme #smenigeria #profits#businessowners #businessplan#entrepreneurship #entrepreneur#blockchain #crypto #cointelegraph#bitcoinprice #mining #cryptocurrencies#bch #bitcoins #litecoin #investment#investor #stockmarket #stocks #getrich#makemoney #makemoneyonline#mentorship #mentoring #xrp #bitfinex#altcoins,Hashtags_.#Tech #virtualreality #IoT #Machinelearning,Hashtags_[#Infographic] #Wearable #Sensors #MachineLearning#IoT #BigData #DigitalTransformation#futureofwork #marketing #analytics#bigdata #Cloud #Blogging#ContentMarketing #DigitalMarketing ht: #BigData #MachineLearning #AI #IoT#infograp,Hashtags_thebeautymindset#businessman#quoteoftheday #businessowner#businesswoman #success #grind#motivation #motivational #lifestyle#happiness #entrepreneurs#entrepreneurlife #business #working #founder#startup #money #magazine #moneymaker#startuplife #successful #passion #inspiredaily#hardwork #hardworkpaysoff #desire,Hashtags_ #datascience #data #tech #technology#future #machinelearning #ai#visualizations #dataisbeautiful,Hashtags_ #deck .#mac #macintosh#sayhello #apple #stevejobs #ai #evolution#artificialintelligence #machinelearning#terminator #illbeback #technology#computerevolution #computerscience#sciencefiction#computersciencetosciencefiction#tomorrowstechnology #vr #ar #robot#robots #t2 #businessdeck #businessslides#illustration #sketches #drawing
66,4,16,-0.777299,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
15,15,20,0.027859,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
70,8,23,0.252714,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
82,9,17,-0.095861,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,3,11,-0.112553,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,22,30,-0.914765,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74,1,6,-0.198960,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,14,18,1.925871,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
98,11,24,1.076527,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51,12,20,1.310220,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [85]:
y_train_likes

66     31
15     53
70     21
82     31
30     90
     ...
61     10
74     35
14     28
98    222
51    157
Name: Likes, Length: 75, dtype: int64

In [94]:
y_train_time

66    2 hours
15    3 hours
70    2 hours
82    2 hours
30    2 hours
       ...
61    3 hours
74    2 hours
14    3 hours
98    3 hours
51    4 hours
Name: Time since posted, Length: 75, dtype: object

In [88]:
# Encode categorical features
data = pd.get_dummies(data, columns=['Time since posted'], drop_first=True)

In [89]:
from sklearn.ensemble import RandomForestRegressor

In [90]:
# Model for predicting likes
model_likes = RandomForestRegressor()

In [91]:
model_likes.fit(X_train, y_train_likes)

RandomForestRegressor()

In [92]:
# Model for predicting time since posted
model_time = RandomForestRegressor()

In [93]:
model_time.fit(X_train, y_train_time)

ValueError: could not convert string to float: '2 hours'